# disorter thresholds depending on how disorder is predicted.
METAPREDICT_DISORDER_THRESHOLD=0.42
METAPREDICT_HYBRID_DISORDER_THRESHOLD_COOPERATIVE = 0.65
METAPREDICT_HYBRID_DISORDER_THRESHOLD_NONCOOPERATIVE = 0.50
METAPREDICT_LEGACY_THRESHOLD = 0.42
METAPREDICT_V2_THRESHOLD=0.5
METAPREDICT_V3_THRESHOLD=0.5

# set the current default network for metapredict.
DEFAULT_NETWORK = 'V3'
DEFAULT_NETWORK_PLDDT = 'V2'
