# Regression test: metapredict's disorder scores must stay consistent with the
# stored ground-truth baselines. These baselines (generated by
# input_data/generate_ground_truth.py) are the reference for confirming that
# changes such as batch size or device selection do not alter predicted scores.
#
# Predictions are made on CPU (always available and reproducible) and compared to
# the CPU baselines. A generous tolerance absorbs platform-level float differences
# while still catching any real regression (which would be orders of magnitude
# larger).

import os

import numpy as np
import protfasta
import pytest

import metapredict as meta

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "input_data")
FASTA = os.path.join(DATA, "ground_truth_500_seqs.fasta")

# use a subset of the 500 sequences to keep the test fast
_all_seqs = protfasta.read_fasta(FASTA, invalid_sequence_action="convert")
KEYS = list(_all_seqs.keys())[:120]
SUBSET = {k: _all_seqs[k] for k in KEYS}

GT_TOL = 1e-3  # generous: catches regressions, tolerates cross-platform CPU float drift


@pytest.mark.parametrize("network_version", ["1", "2", "3"])
def test_disorder_cpu_matches_ground_truth(network_version):
    gt = np.load(os.path.join(DATA, f"ground_truth_500_v{network_version}_cpu.npy"),
                 allow_pickle=True).item()
    preds = meta.predict_disorder(SUBSET, version=network_version, device="cpu",
                                  round_values=False, return_numpy=True, show_progress_bar=False)
    for k in KEYS:
        assert np.allclose(preds[k][1], gt[k], atol=GT_TOL), \
            f"v{network_version}: scores for {k!r} diverged from the ground-truth baseline"
